modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/polserull/European-Railways-Addon/issues"

[[mods]]
modId = "europeanrail"
version = "${version}"
displayName = "European Railways Addon"
displayURL = "https://modrinth.com/mod/european-railways-addon"

authors = "[Creator] pølserull, [Support] szandorthe13th"
description = "A MTR Addon thats various blocks and mechanics from european railways!"
logoFile = "icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.britishrail]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.britishrail]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.britishrail]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.britishrail]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
