modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv2"
issueTrackerURL="https://github.com/polserull/british-rail/issues"

[[mods]]
modId = "britishrail"
version = "${version}"
displayName = "britishrail"
displayURL = "https://github.com/polserull/british-rail/"

authors = "polserull"
description = "britishrail"
logoFile = "icon.png"

displayTest = "IGNORE_ALL_VERSION"

[[dependencies.britishrail]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.britishrail]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.britishrail]]
modId = "architectury"
mandatory = true
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.britishrail]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"
